### ISSUE TITLE
Input files do not correspond with each other

### ISSUE THREAD

**Issue by aakashsur** [yan-cri/DEAPP-shiny#1]
I kept getting this error when uploading a multi-factor design:
```
Warning: Error in ..stacktraceon..: Input files do not correspond with each other. 
Stack trace (innermost first):
    82: isolate
    81: renderText [path/server.R#965]
    80: func
    79: origRenderFunc
    78: output$errorInputMulti
     1: shiny::runApp
```

It seems that the application prefixed an "X" to my column names from my count file for some reason? 

```
 "X8hr.control.1"   "X8hr.control.2"   "X8hr.lysosome.1"  "X8hr.lysosome.2" 
 "X24hr.control.1"  "X24hr.control.2"  "X24hr.lysosome.1" "X24hr.lysosome.2"
 "X48hr.control.1"  "X48hr.control.2"  "X48hr.lysosome.1" "X48hr.lysosome.2"
```
And the fix was to add the "X" to my meta data file

Samples | Timepoint | Treatment 
-- | -- | -- 
X8hr-control_1 | 8 | Control 
X8hr-control_2 | 8 | Control 
X8hr-lysosome_1 | 8 | Lysosome 
X8hr-lysosome_2 | 8 | Lysosome 
X24hr-control_1 | 24 | Control 
X24hr-control_2 | 24 | Control 
X24hr-lysosome_1 | 24 | Lysosome 
X24hr-lysosome_2 | 24 | Lysosome 
X48hr-control_1 | 48 | Control 
X48hr-control_2 | 48 | Control 
X48hr-lysosome_1 | 48 | Lysosome 
X48hr-lysosome_2 | 48 | Lysosome 

I couldn't diagnose why it was behaving this way.

**Comment by yan-cri** [comment]
Hi,

Could you please send me your input files to debug? From your talking, I am unsure what cause this error.

Best,
Yan


On Feb 18, 2019, at 10:38 PM, Aakash Sur <notifications@github.com<mailto:notifications@github.com>> wrote:


I kept getting this error when uploading a multi-factor design:

Warning: Error in ..stacktraceon..: Input files do not correspond with each other.
Stack trace (innermost first):
    82: isolate
    81: renderText [/Users/aakashsur/Desktop/Myler/Zilberstein/DEApp/server.R#965]
    80: func
    79: origRenderFunc
    78: output$errorInputMulti
     1: shiny::runApp


It seems that the application prefixed an "X" to my column names from my count file for some reason?

 "X8hr.control.1"   "X8hr.control.2"   "X8hr.lysosome.1"  "X8hr.lysosome.2"
 "X24hr.control.1"  "X24hr.control.2"  "X24hr.lysosome.1" "X24hr.lysosome.2"
 "X48hr.control.1"  "X48hr.control.2"  "X48hr.lysosome.1" "X48hr.lysosome.2"


And the fix was to add the "X" to my meta data file

Samples Timepoint       Treatment
X8hr-control_1  8       Control
X8hr-control_2  8       Control
X8hr-lysosome_1 8       Lysosome
X8hr-lysosome_2 8       Lysosome
X24hr-control_1 24      Control
X24hr-control_2 24      Control
X24hr-lysosome_1        24      Lysosome
X24hr-lysosome_2        24      Lysosome
X48hr-control_1 48      Control
X48hr-control_2 48      Control
X48hr-lysosome_1        48      Lysosome
X48hr-lysosome_2        48      Lysosome

I couldn't diagnose why it was behaving this way.

**Comment by aakashsur** [comment]
Okay, I've diagnosed the issue. If the sample names start with a number, it breaks the program. So changing my sample name from `8hr_control_1` to `control_8hr_1` fixed the issues. 

Any thoughts on how to handle the error?

**Comment by yan-cri** [comment]
In my opinion, this is cause by R program by itself.

In my opinion, if I would like to improve, I would like to rename all input sample names together with sample names in the metadata table by adding a prefix such as ’sample’. This might solve this error.

Thanks for your feedback.

Best,
Yan


On Feb 19, 2019, at 2:23 PM, Aakash Sur <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, I've diagnosed the issue. If the sample names start with a number, it breaks the program. So changing my sample name from 8hr_control_1 to control_8hr_1 fixed the issues.

Any thoughts on how to handle the error?
